// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRisk.Infrastructure.Persistence;

#nullable disable

namespace VendorRisk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VendorRiskDbContext))]
    [Migration("20260827022557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<List<string>>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("SlaUptime")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRisk.Domain.Vendors.VendorDocuments", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("contract_valid");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("pentest_report_valid");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_policy_valid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
