// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRisk.Infrastructure.Persistence;

#nullable disable

namespace VendorRisk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VendorRiskDbContext))]
    [Migration("20260827051957_AddCertificateTables")]
    partial class AddCertificateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRisk.Domain.Vendors.SecurityCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorCertificate", b =>
                {
                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.Property<int>("CertificateId")
                        .HasColumnType("integer");

                    b.HasKey("VendorId", "CertificateId");

                    b.HasIndex("CertificateId");

                    b.ToTable("vendor_certificates", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("SlaUptime")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorCertificate", b =>
                {
                    b.HasOne("VendorRisk.Domain.Vendors.SecurityCertificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VendorRisk.Domain.Vendors.VendorProfile", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VendorRisk.Domain.Vendors.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRisk.Domain.Vendors.VendorDocuments", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("contract_valid");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("pentest_report_valid");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_policy_valid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
